CREATE DATABASE CONSULTA
GO
USE CONSULTA
GO

--TABLAS:

/*
ERP: ID, NOMBRE
USUARIO: ID, NOMBRE, APELLIDO, TELEFONO, ID_ERP
ESPECIALIDAD: ID_ESP, NOMBRE
MEDICO: ID, NOMBRE, APELLIDO, ID_ESPECIALIDAD
CITA: ID, FECHA, HORA, ID_USUARIO, ID_MEDICO
*/

--CREACIÓN DE TABLAS:
CREATE TABLE ERP(
ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
NOMBRE VARCHAR(20) NOT NULL
)

CREATE TABLE USUARIOS(
ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
NOMBRE NVARCHAR(20) NOT NULL,
APELLIDO NVARCHAR(20) NOT NULL,
TELEFONO CHAR(10) UNIQUE,
ID_ERP INT NOT NULL
FOREIGN KEY (ID_ERP) REFERENCES ERP(ID)
)

CREATE TABLE ESPECIALIDAD(
ID_ESP INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
NOMBRE VARCHAR(30) NOT NULL
)

CREATE TABLE MEDICO(
ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
NOMBRE VARCHAR(30) NOT NULL,
APELLIDO VARCHAR(30) NOT NULL,
ID_ESPECIALIDAD INT NOT NULL
FOREIGN KEY (ID_ESPECIALIDAD) REFERENCES ESPECIALIDAD(ID_ESP)
)

CREATE TABLE CITA(
ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
FECHA DATE NOT NULL,
HORA TIME NOT NULL,
ID_USUARIO INT NOT NULL,
ID_MEDICO INT NOT NULL
FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID),
FOREIGN KEY (ID_MEDICO) REFERENCES MEDICO(ID)
)


--CONSULTAS:
--TABLA ERP
SELECT * 
FROM ERP

--TABLA USUARIOS
SELECT *
FROM USUARIOS

--TABLA ESPECIALIDAD
SELECT * 
FROM ESPECIALIDAD

--TABLA MEDICO
SELECT *
FROM MEDICO

--TABLA CITAS
SELECT *
FROM CITA

--INGRESO DE DATOS:
--ERP
INSERT INTO ERP (NOMBRE)
VALUES
('SURA'),
('Nueva Eps'),
('Salud Total')

--USUARIOS
INSERT INTO USUARIOS(NOMBRE, APELLIDO, TELEFONO, ID_ERP)
VALUES
('Maria', 'Monsalve', 3456783245, 2),
('Juan','Buitrago', 3123456789, 1),
('Felipe','Olaya', 3987654321, 1)

--ESPECIALIDAD
INSERT INTO ESPECIALIDAD(NOMBRE)
VALUES
('Cardiologia'),
('Neurologia'),
('Reumatologia')

--MEDICO
INSERT INTO MEDICO(NOMBRE, APELLIDO,ID_ESPECIALIDAD)
VALUES 
('Armando', 'Casas', 1),
('Maria', 'Cataño', 2),
('Lina', 'Ramirez', 3),
('Mark', 'Larsson', 1)

--CITA
INSERT INTO CITA (FECHA, HORA, ID_USUARIO, ID_MEDICO)
VALUES
('2023-06-23','09:30:00',2,2),
('2023-09-26', '12:45:00',3,2),
('2023-09-28', '8:30:00',2,1),
('2023-09-12', '10:45:00',2,1)

--mostrar usuarios que el nombre comience con C
SELECT *
FROM USUARIOS
WHERE NOMBRE LIKE 'J%'

--citas programadas entre 1 de enero y 15 de septiembre
SELECT * 
FROM CITA
WHERE FECHA BETWEEN '2023-01-01' AND '2023-09-01'

--citas programadas en x fecha e id_medico escogido por usted
SELECT *
FROM CITA
WHERE FECHA = '2023-06-23' AND ID_MEDICO = 2

--citas con x medico y x especialidad
SELECT CITA.*, MEDICO.NOMBRE, MEDICO.APELLIDO, ESPECIALIDAD.NOMBRE
FROM CITA
JOIN MEDICO 
ON CITA.ID_MEDICO = MEDICO.ID
JOIN ESPECIALIDAD
ON MEDICO.ID_ESPECIALIDAD = ESPECIALIDAD.ID_ESP
WHERE MEDICO.NOMBRE = 'Armando' AND ESPECIALIDAD.NOMBRE = 'Cardiologia'
--usuario que no pertenezca a sura
SELECT *
FROM USUARIOS
JOIN ERP
ON USUARIOS.ID_ERP = ERP.ID
WHERE ERP.NOMBRE <> 'Sura'


--MODIFICADORES
--agregar a la tabla citas el atributo cuota moderadora y actualizar cada registro con este campo
ALTER TABLE CITA 
ADD CUOTA_MODERADORA INT CHECK (CUOTA_MODERADORA >= 4100)

UPDATE CITA SET CUOTA_MODERADORA = 4200

--RESTRICCIONES
--unique: se utiliza para evitar repetir valores (clave primaria viene incorporada con resitrcciones unique)
--check: valida la informacion ingresada en un campo
--default: proporciona un valor predeterminado a un campo que no registra informacion.


--tabla usuario agregar atributo correo con restriccion default
ALTER TABLE USUARIOS
ADD EMAIL NVARCHAR(50)

ALTER TABLE USUARIOS 
ADD CONSTRAINT DF_CORREO DEFAULT 'USUARIO@MAIL.COM'
FOR EMAIL
--validar que cuota moderadora sea mayor o igual a 4100
-- IR A LA LINEA 148 

--FUNCIONES:
/*
SUM: SUMA DE VALORES
MAX: MUESTRA EL VALOR MAXIMO
MIN: MUESTRA EL VALOR MINIMO
AVG: CALCULAR EL PROMEDIO
COUNT: CUENTA CANTIDAD DE REGISTROS
DISTINCT: MUESTRA SOLAMENTE VALORES DIFERENTES
*/

--CALCULAR EL TOTAL DE CUOTAS MODERADORAS REGISTRADAS
SELECT SUM(CUOTA_MODERADORA) AS 'SUMA DE CUOTAS MODERADORAS'
FROM CITA

--CONTAR USUARIOS ID_ERP DE SURA
SELECT COUNT(USUARIOS.ID) AS 'USUARIOS CON SURA'
FROM USUARIOS
JOIN ERP
ON USUARIOS.ID_ERP = ERP.ID
WHERE USUARIOS.ID_ERP = 1