CREATE CONSULTA
GO
USE CONSULTA
GO

--TABLAS:

/*
ERP: ID, NOMBRE
USUARIO: ID, NOMBRE, APELLIDO, TELEFONO, ID_ERP
ESPECIALIDAD: ID_ESP, NOMBRE
MEDICO: ID, NOMBRE, APELLIDO, ID_ESPECIALIDAD
CITA: ID, FECHA, HORA, ID_USUARIO, ID_MEDICO
*/

--CREACIÓN DE TABLAS:
CREATE TABLE ERP(
ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
NOMBRE VARCHAR(20) NOT NULL
)

CREATE TABLE USUARIOS(
ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
NOMBRE NVARCHAR(20) NOT NULL,
APELLIDO NVARCHAR(20) NOT NULL,
TELEFONO CHAR(10),
ID_ERP INT NOT NULL
FOREIGN KEY (ID_ERP) REFERENCES ERP(ID)
)

CREATE TABLE ESPECIALIDAD(
ID_ESP INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
NOMBRE VARCHAR(30) NOT NULL
)

CREATE TABLE MEDICO(
ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
NOMBRE VARCHAR(30) NOT NULL,
APELLIDO VARCHAR(30) NOT NULL,
ID_ESPECIALIDAD INT NOT NULL
FOREIGN KEY (ID_ESPECIALIDAD) REFERENCES ESPECIALIDAD(ID_ESP)
)

CREATE TABLE CITA(
ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
FECHA DATE NOT NULL,
HORA DATETIME NOT NULL,
ID_USUARIO INT NOT NULL,
ID_MEDICO INT NOT NULL
FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID),
FOREIGN KEY (ID_MEDICO) REFERENCES MEDICO(ID)
)